version: 1.0.{build}
configuration: Release
init:
- cmd: >-
    tzutil /s "Eastern Standard Time"
    choco install cake.portable -r -y
before_build:
- cmd: cake
build:
  publish_nuget: true
  verbosity: minimal
before_package:
- cmd: nuget restore
notifications:
- provider: Slack
  incoming_webhook: 
    secure: jAHwieC/ls9GRYV3YawixFkHoUekBo17Sq63Ik5AYYKHbm+GZwLKJy9ni7gsxwXVwA+79fbacsARTacf1bvYSJFALusnWuqqBa208OqYvFc=
  channel: builds
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false